name: CycloneDX (SBOM) Challenge using Github Actions for SBOM ASE CL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  npm-audit-scan-job:
    name: CycloneDX (SBOM) Challenge
    runs-on: ubuntu-latest
    steps:
      - name: Step1 Download the Source Code
        uses: actions/checkout@v4

      - name: Step2 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ''
          # node-version: '1.19.3'

      - name: Step3 Install Dependencies
        run: npm install
      
      - name: Step4 Install cyclonedx
        run: npm install --global @cyclonedx/cyclonedx-npm
        
      - name: Step5 NPM Audit Scan and Generate Report in JSON Format (default)
        run: cyclonedx-npm -v -o sca_cyclone.json
        #run: cyclonedx-npm -v
        continue-on-error: true

      - name: Step6 send POST request ASE
        run: |
          # curl -X POST -H "Content-Type: application/json" -d '{"key1": "value1", "key2": "value2"}'  http://35.219.137.114:8880/callback http://35.219.131.130:8880/callback
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@sca_cyclone" http://35.219.131.130:8880/callback
          
