name: CycloneDX (SBOM) Challenge using Github Actions for SBOM ASE CL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  npm-audit-scan-job:
    name: CycloneDX (SBOM) Challenge
    runs-on: ubuntu-latest
    steps:
      - name: Step1 Download the Source Code
        uses: actions/checkout@v4

      - name: Step2 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ''
          # node-version: '1.19.3'

      - name: Step3 Install Dependencies
        run: npm install
      
      - name: Step4 Install cyclonedx
        run: npm install --global @cyclonedx/cyclonedx-npm
        
      - name: Step5 NPM Audit Scan and Generate Report in JSON Format (default)
        run: cyclonedx-npm
        # run: cyclonedx-bom --json
        continue-on-error: true

      #- name: Step5 Upload NPM Audit Scan Report to GitHub
       # uses: actions/upload-artifact@v4
        #with:
         # name: upload sbom report to github.com
          #path: package.json

      - name: Step6 send POST request ASE
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" -F "file=@package.json" http://35.219.146.163:8880/callback
